-- lvds_tx.vhd

-- Generated using ACDS version 20.1 720

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lvds_tx is
	port (
		tx_in  : in  std_logic_vector(0 downto 0) := (others => '0'); --  tx_in.tx_in
		tx_out : out std_logic_vector(0 downto 0)                     -- tx_out.tx_out
	);
end entity lvds_tx;

architecture rtl of lvds_tx is
	component altera_soft_lvds_tx_twD5CSXW is
		port (
			tx_in  : in  std_logic_vector(0 downto 0) := (others => 'X'); -- tx_in
			tx_out : out std_logic_vector(0 downto 0)                     -- tx_out
		);
	end component altera_soft_lvds_tx_twD5CSXW;

begin

	lvds_tx_inst : component altera_soft_lvds_tx_twD5CSXW
		port map (
			tx_in  => tx_in,  --  tx_in.tx_in
			tx_out => tx_out  -- tx_out.tx_out
		);

end architecture rtl; -- of lvds_tx
