-- lvds_rx.vhd

-- Generated using ACDS version 23.1 993

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lvds_rx is
	port (
		data  : in  std_logic_vector(0 downto 0) := (others => '0'); --  data.data
		clock : in  std_logic                    := '0';             -- clock.clock
		q     : out std_logic_vector(0 downto 0)                     --     q.q
	);
end entity lvds_rx;

architecture rtl of lvds_rx is
	component altera_soft_lvds_rx_uCmNW05P is
		port (
			data  : in  std_logic_vector(0 downto 0) := (others => 'X'); -- data
			clock : in  std_logic                    := 'X';             -- clock
			q     : out std_logic_vector(0 downto 0)                     -- q
		);
	end component altera_soft_lvds_rx_uCmNW05P;

begin

	lvds_rx_inst : component altera_soft_lvds_rx_uCmNW05P
		port map (
			data  => data,  --  data.data
			clock => clock, -- clock.clock
			q     => q      --     q.q
		);

end architecture rtl; -- of lvds_rx
