#!/bin/bash
export TODAY=`date +'%Y%m%d'`
export VERSION=`cat VERSION`
echo "D:$TODAY:"
echo "V:$VERSION:"
cat ../firmware/ECLAIREXL.bin |sed -e "s/Date:YYYYMMDD Core:XX/Date:$TODAY Core:$VERSION/" > ../firmware/ECLAIREXL.bin_dated
../firmware/mif_file_stuff/zpuromgen ../firmware/ECLAIREXL.bin_dated  > zpu_rom.mif_insidesv3
cat ../firmware/mif_file_stuff/rom_prologue_40.vhd  zpu_rom.mif_insidesv3 ../firmware/mif_file_stuff/rom_epilogue.vhd  > zpu_romv3.mif

if [ $1 != "BUILD" ]; then
    echo Updating existing

    cp zpu_romv3.mif build_v3rom/zpu_rom.mif
    quartus_cdb --update_mif build_v3rom/atari800core_eclaireXLv3.qpf
    quartus_asm build_v3rom/atari800core_eclaireXLv3.qpf
    
    pushd build_v3rom/
    quartus_cpf --convert ../convertv3.cof
    popd
else
    echo Skipping update
fi

