#!/bin/bash
export TODAY=`date +'%Y%m%d'`
export VERSION=`cat VERSION`
echo "D:$TODAY:"
echo "V:$VERSION:"
if [[ ! -f ../firmware_eclairexl/ECLAIREXL.bin ]] ; then
    echo 'File "../firmware_eclairexl/ECLAIREXL.bin" is not there, aborting.'
    exit
fi

cat ../firmware_eclairexl/ECLAIREXL.bin |sed -e "s/Date:YYYYMMDD Core:XX/Date:$TODAY Core:$VERSION/" > ../firmware_eclairexl/ECLAIREXL.bin_dated
../firmware_eclairexl/mif_file_stuff/zpuromgen ../firmware_eclairexl/ECLAIREXL.bin_dated  > zpu_rom.mif_insidesv2
cat ../firmware_eclairexl/mif_file_stuff/rom_prologue_40.vhd  zpu_rom.mif_insidesv2 ../firmware_eclairexl/mif_file_stuff/rom_epilogue.vhd  > zpu_romv2.mif

if [ $1 != "BUILD" ]; then
    echo Updating existing

    cp zpu_romv2.mif build_A4EBArom/zpu_rom.mif
    quartus_cdb --update_mif build_A4EBArom/atari800core_eclaireXLv2.qpf
    quartus_asm build_A4EBArom/atari800core_eclaireXLv2.qpf
    
    pushd build_A4EBArom/
    quartus_cpf --convert ../convertv2.cof
    popd
else
    echo Skipping update
fi

