pll_acore_reconfig_sim/pll_acore_reconfig.vhd
pll_acore_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_top.v
pll_acore_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_core.v
pll_acore_reconfig_sim/altera_pll_reconfig/altera_std_synchronizer.v
