# TCL File Generated by Component Editor 14.0
# Mon Dec 29 22:04:48 GMT 2014
# DO NOT MODIFY


# 
# avalon_arm_regs "avalon_arm_regs" v1.0
#  2014.12.29.22:04:48
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avalon_arm_regs
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_arm_regs
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_arm_regs
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_arm_regs
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_arm_regs.vhdl VHDL PATH avalon_arm_regs.vhdl TOP_LEVEL_FILE
add_fileset_file sio_device.vhdl VHDL PATH common/a8core/sio_device.vhdl
add_fileset_file complete_address_decoder.vhdl VHDL PATH common/components/complete_address_decoder.vhdl
add_fileset_file pokey.vhdl VHDL PATH common/a8core/pokey.vhdl
add_fileset_file pokey_countdown_timer.vhdl VHDL PATH common/a8core/pokey_countdown_timer.vhdl
add_fileset_file pokey_keyboard_scanner.vhdl VHDL PATH common/a8core/pokey_keyboard_scanner.vhdl
add_fileset_file pokey_mixer.vhdl VHDL PATH common/a8core/pokey_mixer.vhdl
add_fileset_file pokey_mixer_mux.vhdl VHDL PATH common/a8core/pokey_mixer_mux.vhdl
add_fileset_file pokey_noise_filter.vhdl VHDL PATH common/a8core/pokey_noise_filter.vhdl
add_fileset_file pokey_poly_17_9.vhdl VHDL PATH common/a8core/pokey_poly_17_9.vhdl
add_fileset_file pokey_poly_4.vhdl VHDL PATH common/a8core/pokey_poly_4.vhdl
add_fileset_file pokey_poly_5.vhdl VHDL PATH common/a8core/pokey_poly_5.vhdl


# 
# parameters
# 
add_parameter platform INTEGER 1
set_parameter_property platform DEFAULT_VALUE 1
set_parameter_property platform DISPLAY_NAME platform
set_parameter_property platform TYPE INTEGER
set_parameter_property platform UNITS None
set_parameter_property platform ALLOWED_RANGES -2147483648:2147483647
set_parameter_property platform HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_N reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 ADDRESS address Input 11
add_interface_port avalon_slave_0 READ read Input 1
add_interface_port avalon_slave_0 READDATA readdata Output 32
add_interface_port avalon_slave_0 WRITE write Input 1
add_interface_port avalon_slave_0 WRITEDATA writedata Input 32
add_interface_port avalon_slave_0 BYTEENABLE byteenable Input 4
add_interface_port avalon_slave_0 CHIPSELECT chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end POKEY_ENABLE pokey_enable Input 1
add_interface_port conduit_end IN1 in1 Input 32
add_interface_port conduit_end IN2 in2 Input 32
add_interface_port conduit_end IN3 in3 Input 32
add_interface_port conduit_end IN4 in4 Input 32
add_interface_port conduit_end OUT1 out1 Output 32
add_interface_port conduit_end OUT2 out2 Output 32
add_interface_port conduit_end OUT3 out3 Output 32
add_interface_port conduit_end OUT4 out4 Output 32
add_interface_port conduit_end OUT5 out5 Output 32
add_interface_port conduit_end OUT6 out6 Output 32
add_interface_port conduit_end SIO_DATA_IN sio_data_in Output 1
add_interface_port conduit_end SIO_COMMAND sio_command Input 1
add_interface_port conduit_end SIO_DATA_OUT sio_data_out Input 1

